services:
  mysql:
    image: mysql:9.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - task-manager-mysql-data:/var/lib/mysql
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - task-manager-network

  minio:
    image: minio/minio:RELEASE.2024-09-13T20-26-02Z-cpuv1
    container_name: minio
    restart: always
    command: 'minio server /data/minio --console-address ":9001"'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - task-manager-minio-data:/data/minio
    networks:
      - task-manager-network

  #server

  #client

volumes:
  task-manager-mysql-data:
  task-manager-minio-data:

networks:
  task-manager-network:
    driver: bridge