services:
  mysql:
    image: mysql:9.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - task-manager-mysql-data:/var/lib/mysql
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - task-manager-network

  #server

  #client

volumes:
  task-manager-mysql-data:

networks:
  task-manager-network:
    driver: bridge